/**
 * Unified sidebar for all of Vantage docs.
 *
 * Tree shape per spec:
 *   GET STARTED · CONCEPTS · PLATFORM · REFERENCE · ABOUT
 *
 * Items are mostly autogenerated from the directory tree; section
 * headers are hand-pinned so they group consistently.
 */

module.exports = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'get-started/index'},
      items: [
        {type: 'doc', id: 'get-started/sign-up'},
        {type: 'doc', id: 'get-started/invite-intro'},
        {type: 'doc', id: 'get-started/create-cloud'},
        {type: 'doc', id: 'get-started/create-cluster-intro'},
        {type: 'doc', id: 'get-started/create-job-script-intro'},
        {type: 'doc', id: 'get-started/create-job-submission-intro'},
        {type: 'doc', id: 'get-started/notebook-intro'},
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'concepts/index'},
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Platform</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Jobs',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/jobs/index'},
      items: [
        {type: 'doc', id: 'platform/jobs/get-started'},
        {type: 'doc', id: 'platform/jobs/concepts'},
        {
          type: 'category',
          label: 'Scripts',
          link: {type: 'doc', id: 'platform/jobs/scripts/index'},
          items: [
            {type: 'doc', id: 'platform/jobs/scripts/creating'},
            {type: 'doc', id: 'platform/jobs/scripts/managing'},
            {type: 'doc', id: 'platform/jobs/scripts/reference'},
          ],
        },
        {
          type: 'category',
          label: 'Templates',
          link: {type: 'doc', id: 'platform/jobs/templates/index'},
          items: [
            {type: 'doc', id: 'platform/jobs/templates/creating'},
            {type: 'doc', id: 'platform/jobs/templates/using'},
            {type: 'doc', id: 'platform/jobs/templates/managing'},
            {type: 'doc', id: 'platform/jobs/templates/reference'},
          ],
        },
        {
          type: 'category',
          label: 'Submissions',
          link: {type: 'doc', id: 'platform/jobs/submissions/index'},
          items: [
            {type: 'doc', id: 'platform/jobs/submissions/submitting'},
            {type: 'doc', id: 'platform/jobs/submissions/monitoring'},
            {type: 'doc', id: 'platform/jobs/submissions/lifecycle'},
            {type: 'doc', id: 'platform/jobs/submissions/reference'},
          ],
        },
        {type: 'doc', id: 'platform/jobs/catalog/index'},
      ],
    },
    {
      type: 'category',
      label: 'Storage',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/storage/index'},
      items: [{type: 'autogenerated', dirName: 'platform/storage'}],
    },
    {
      type: 'category',
      label: 'Workbench',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/workbench/index'},
      items: [{type: 'autogenerated', dirName: 'platform/workbench'}],
    },
    {
      type: 'category',
      label: 'Clusters',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/clusters/index'},
      items: [{type: 'autogenerated', dirName: 'platform/clusters'}],
    },
    {
      type: 'category',
      label: 'Compute providers',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/compute-providers/index'},
      items: [{type: 'autogenerated', dirName: 'platform/compute-providers'}],
    },
    {
      type: 'category',
      label: 'Federations',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/federations/index'},
      items: [{type: 'autogenerated', dirName: 'platform/federations'}],
    },
    {
      type: 'category',
      label: 'IAM',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/iam/index'},
      items: [{type: 'autogenerated', dirName: 'platform/iam'}],
    },
    {
      type: 'category',
      label: 'Teams',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/teams/index'},
      items: [{type: 'autogenerated', dirName: 'platform/teams'}],
    },
    {
      type: 'category',
      label: 'Licenses',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/licenses/index'},
      items: [{type: 'autogenerated', dirName: 'platform/licenses'}],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Reference</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'CLI',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'reference/cli/index'},
      items: [{type: 'autogenerated', dirName: 'reference/cli'}],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'reference/sdk/index'},
      items: [{type: 'autogenerated', dirName: 'reference/sdk'}],
    },
    {
      type: 'category',
      label: 'API',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'reference/api/index'},
      items: [{type: 'autogenerated', dirName: 'reference/api'}],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">About</div>',
      defaultStyle: true,
    },
    {type: 'doc', id: 'changelog'},
    {type: 'doc', id: 'support'},
    {type: 'doc', id: 'glossary'},
  ],
};
