/**
 * Unified sidebar for all of Vantage docs.
 *
 * Tree shape per spec:
 *   GET STARTED · CONCEPTS · PRODUCTS · PLATFORM · REFERENCE · ABOUT
 *
 * Items are mostly autogenerated from the directory tree; section
 * headers are hand-pinned so they group consistently.
 */

module.exports = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Get started',
      collapsible: true,
      collapsed: false,
      link: {type: 'doc', id: 'get-started/index'},
      items: [{type: 'autogenerated', dirName: 'get-started'}],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'concepts/index'},
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Products</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Jobs',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'products/jobs/index'},
      items: [{type: 'autogenerated', dirName: 'products/jobs'}],
    },
    {
      type: 'category',
      label: 'Storage',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'products/storage/index'},
      items: [{type: 'autogenerated', dirName: 'products/storage'}],
    },
    {
      type: 'category',
      label: 'Workbench',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'products/workbench/index'},
      items: [{type: 'autogenerated', dirName: 'products/workbench'}],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Platform</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Clusters',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/clusters/index'},
      items: [{type: 'autogenerated', dirName: 'platform/clusters'}],
    },
    {
      type: 'category',
      label: 'Compute providers',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/compute-providers/index'},
      items: [{type: 'autogenerated', dirName: 'platform/compute-providers'}],
    },
    {
      type: 'category',
      label: 'Federations',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/federations/index'},
      items: [{type: 'autogenerated', dirName: 'platform/federations'}],
    },
    {
      type: 'category',
      label: 'IAM',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/iam/index'},
      items: [{type: 'autogenerated', dirName: 'platform/iam'}],
    },
    {
      type: 'category',
      label: 'Teams',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/teams/index'},
      items: [{type: 'autogenerated', dirName: 'platform/teams'}],
    },
    {
      type: 'category',
      label: 'Licenses',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'platform/licenses/index'},
      items: [{type: 'autogenerated', dirName: 'platform/licenses'}],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">Reference</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'CLI',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'reference/cli/index'},
      items: [{type: 'autogenerated', dirName: 'reference/cli'}],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'reference/sdk/index'},
      items: [{type: 'autogenerated', dirName: 'reference/sdk'}],
    },
    {
      type: 'category',
      label: 'API',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'reference/api/index'},
      items: [{type: 'autogenerated', dirName: 'reference/api'}],
    },
    {
      type: 'html',
      value: '<div class="sidebar-section-label">About</div>',
      defaultStyle: true,
    },
    {type: 'doc', id: 'changelog'},
    {type: 'doc', id: 'support'},
    {type: 'doc', id: 'glossary'},
  ],
};
