/**
 * Platform documentation sidebar configuration
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a "Next" and "Previous" navigation
 * - automatically add "Edit this page" links
 */

const sidebars = {
  platform: [
    {
      type: 'doc',
      id: 'index',
      label: 'Platform Overview',
    },
    {
      type: 'category',
      label: 'Jobs',
      link: {
        type: 'doc',
        id: 'jobs/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'jobs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Clusters',
      link: {
        type: 'doc',
        id: 'clusters/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'clusters',
        },
      ],
    },
    {
      type: 'category',
      label: 'Storage',
      link: {
        type: 'doc',
        id: 'storage/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'storage',
        },
      ],
    },
    {
      type: 'category',
      label: 'Compute Providers',
      link: {
        type: 'doc',
        id: 'compute-providers/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'compute-providers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Notebooks',
      link: {
        type: 'doc',
        id: 'notebooks/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'notebooks',
        },
      ],
    },
    {
      type: 'category',
      label: 'Remote Desktops',
      link: {
        type: 'doc',
        id: 'remote-desktops/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'remote-desktops',
        },
      ],
    },
    {
      type: 'category',
      label: 'Teams',
      link: {
        type: 'doc',
        id: 'teams/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'teams',
        },
      ],
    },
    {
      type: 'category',
      label: 'Licenses',
      link: {
        type: 'doc',
        id: 'licenses/index',
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'licenses',
        },
      ],
    },
  ],
};

module.exports = sidebars;