# Feature Request Template for Vantage Documentation

name: ✨ Feature Request
description: Suggest a new feature or enhancement for the documentation
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - New documentation section
        - Site functionality improvement
        - Better navigation/search
        - Interactive examples
        - Code snippets/samples
        - Mobile experience
        - Accessibility improvement
        - Performance enhancement
        - Developer tools integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the current limitation or pain point
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: Describe your ideal solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: List any alternative solutions you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: input
    id: affected-sections
    attributes:
      label: Affected Documentation Sections
      description: Which parts of the docs would this impact?
      placeholder: Platform, API, CLI, SDK, or specific pages

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help us understand your request
      placeholder: Examples from other sites, mockups, use cases, etc.