---
# tasks/main.yml
- name: Ensure python3 and pip are installed
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true

- name: Create directories for vantage-agent
  file:
    path: /opt/vantage-agent
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create directories for jobbergate-agent
  file:
    path: /opt/jobbergate-agent
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create venv for vantage-agent
  command: python3 -m venv /opt/vantage-agent/venv
  args:
    creates: /opt/vantage-agent/venv/bin/activate
  become: true

- name: Create venv for jobbergate-agent
  command: python3 -m venv /opt/jobbergate-agent/venv
  args:
    creates: /opt/jobbergate-agent/venv/bin/activate
  become: true

- name: Install vantage-agent from PyPI
  command: /opt/vantage-agent/venv/bin/pip install vantage-agent
  become: true

- name: Install jobbergate-agent from PyPI
  command: /opt/jobbergate-agent/venv/bin/pip install jobbergate-agent
  become: true

- name: Create vantage-agent.env
  copy:
    dest: /etc/vantage-agent/vantage-agent.env
    content: |
      VANTAGE_AGENT_OIDC_CLIENT_ID={{ oidc_client_id }}
      VANTAGE_AGENT_OIDC_CLIENT_SECRET={{ oidc_client_secret }}
      VANTAGE_AGENT_CLUSTER_NAME={{ cluster_name }}
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Create jobbergate-agent.env
  copy:
    dest: /etc/jobbergate-agent/jobbergate-agent.env
    content: |
      JOBBERGATE_AGENT_OIDC_CLIENT_ID={{ oidc_client_id }}
      JOBBERGATE_AGENT_OIDC_CLIENT_SECRET={{ oidc_client_secret }}
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Deploy vantage-agent systemd service
  template:
    src: vantage-agent.service.j2
    dest: /etc/systemd/system/vantage-agent.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy jobbergate-agent systemd service
  template:
    src: jobbergate-agent.service.j2
    dest: /etc/systemd/system/jobbergate-agent.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload systemd
  command: systemctl daemon-reload
  become: true

- name: Enable and start vantage-agent
  service:
    name: vantage-agent
    enabled: true
    state: started
  become: true

- name: Enable and start jobbergate-agent
  service:
    name: jobbergate-agent
    enabled: true
    state: started
  become: true
