name: Deploy to staging

on:
  workflow_dispatch:

jobs:
  publish:
    name: Deploy tag
    environment: release
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Build and deploy
        run: |
          yarn install
          yarn build
          npx cdk deploy --ci --require-approval never VantageStagingDocsWebsite
